[package]
name = "assignment"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["Abdul Kareem"]
license = "MIT"
description = "A simple assignment template for personal use."

[template]
path = "template"
entrypoint = "main.typ"
